name: Example Workflow

on: [pull_request]

jobs:
  runs-on: ubuntu-latest
  check-base-branch:
    steps:
      - uses: a-b-r-o-w-n/check-base-branch-action@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          protected-branches: "main"